@shopid = 23056754
@url = https://shopee.tw/api/v4

# 【玩家殿堂】Razer-Gigantus-V2-雷蛇-巨甲蟲V2-布面-電競滑鼠墊 9703364587 
@testItemId = 7279571421

### test get image '_tn' suffix meaning get the size for thumbnail
@imgHash = 10b1e812708dcb7a4be726672d3ba3e5
GET https://cf.shopee.tw/file/{{imgHash}}

### search products
GET {{url}}/search/search_items
?by=pop
&entry_point=ShopByPDP
&match_id={{shopid}}
&order=desc
&page_type=shop
&scenario=PAGE_OTHERS
&version=2
&page=4
&newest=120
User-Agent: 'Googlebot'
Form: ''

### get produt detail 
GET {{url}}/item/get
?itemid={{testItemId}}
&shopid={{shopid}}
User-Agent: 'Googlebot'

### get product shippment
GET {{url}}/pdp/get_shipping
?city=
&district=
&itemid={{testItemId}}
&shopid={{shopid}}
&state=
&town=
User-Agent: 'Googlebot'

### 賣場分類 use : shop_catgory_id
GET {{url}}/shop/get_categories?limit=20&offset=0&shopid={{shopid}}

### signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "username":"timmy",
    "password":"7878787878"
}

### sigin 
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "username":"timmy",
    "password":"7878787878"
}


### get access token accessToken by refresh token from http only cookie
GET http://localhost:8080/auth/accessToken
Cookie: ?